### PR TITLE
Store global logger guard for the lifetime of the actor system

### PR DESCRIPTION
**Pull request by mrjoe7**
This is addressing issue found in #78

### CODE REVIEW

**Comment by mkj** [comment]
Hah, beat me by minutes. Yours looks good, there's a test you could add https://github.com/mkj/riker/commit/084118ffff53ac951b03735f3b98ee557b4bc78d

**Comment by leenozara** [comment]
I’m just wondering if `System` S should require both the logger and the log guard as separate parameters. I can imagine if `System` evolves then using the same approach with other parts will make the number of parameters pretty long. Is a single struct that contains both the logger and guard cleaner? Or is this clunky? Appreciate some thoughts on this before merging.

Thanks

**Comment by mrjoe7** [comment]
I do not expect any additional fields to emerge, but single struct to hold both fields will be nicer.

**Comment by leenozara** [comment]
I think this sets a good precedent re consolidating into a common type.

Thanks @mrjoe7 and @mkj !

**Pull request merged**
