### PR TITLE
Use the stable dashmap, all tests pass on Arm

### LINKED ISSUE #122: Parallel actor creation can deadlock or crash riker
While implementing one of the benchmarks from [actor-framework/benchmarks](https://github.com/actor-framework/benchmarks), I found out that riker sometims deadlocks (hangs) or crashes with an access violation when multiple actors get created simultaneously.

I created a minimal example at [my test repo](https://github.com/hardliner66/riker_bench/tree/access_violation).

The problem seems to be an atomic_load in dashmap, but I'm not sure if this is a bug in dashmap or just misuse on our side.

-----
Tested on:
- Windows 10 (stable-x86_64-pc-windows-msvc 1.44.1)
- Ubuntu 20.04 LTS (stable-x86_64-unknown-linux-gnu 1.44.1)

Additional files:
[stacktrace.txt](https://github.com/riker-rs/riker/files/4854043/stack_trace.txt)

### LINKED ISSUE #131: Tests fail on Arm
The test suite fails to run on Arm, specifically a raspberry pi, the failures seem rooted in dashmap. When looking at dashmap it seems riker is using an unreleased version of dashmap which has a lot of code churn. Would it make sense to use the stable dashmap until its released possibly?

### PR DESCRIPTION
**Pull request by bfrog**
All the tests now pass running on a raspberry pi, where as before they would 
*never* pass

Fixes #131 
Fixes #122

### CODE REVIEW

**Comment by igalic** [comment]
@bfrog could you please rebase this against the current master?

**Comment by nothingismagick** [comment]
This is kind of important, any way to get this moving?

**Comment by hardliner66** [comment]
@bfrog Could update your pull request and resolve the merge conflicts?

**Comment by nothingismagick** [comment]
This PR should be closed.

**Comment by bfrog** [comment]
Thanks for fixing that stuff up

**Pull request closed without merging**
